### ISSUE TITLE
Corregir paginacion.

### ISSUE THREAD

**Issue by XnJaca** [XnJaca/acdemic#8]
# Se muestra la paginacion de forma equivocada.

![Captura de pantalla 2023-10-28 a la(s) 21 57 26](https://github.com/XnJaca/acdemic/assets/114267678/04f1e721-2da5-426a-bcd7-96ae81be694f)

**Comment by AlejandroQuinte** [comment]
El problema viene del back end, el cual si trae lo que debe, solo que si se esta haciendo un filtro visible del front, ese es el problema

recordar siempre mandar el where al get all para que el filtrado sea correcto...

recordar tambien que la ruta de subject debe ser revisada correctamente
no tiene los valores que tienen las demas rutas, verificar con las demas rutas

![image](https://github.com/XnJaca/acdemic/assets/67673448/f6e8890d-f57a-40cc-a277-50114324d0a1)

![image](https://github.com/XnJaca/acdemic/assets/67673448/70c1539a-a9ca-4c04-bf7a-ab8246333f02)

**Comment by AlejandroQuinte** [comment]
Resolviendo el problema desde el back end, arreglando la paginacion de subject
